name = "dhgate-monitor"
main = "cloudflare_app.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# KV Namespace for data storage
[[kv_namespaces]]
binding = "DHGATE_MONITOR_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_ID"

# Custom domain routing
[[routes]]
pattern = "dhgate-monitor.com/*"
zone_name = "dhgate-monitor.com"

[[routes]]
pattern = "www.dhgate-monitor.com/*"
zone_name = "dhgate-monitor.com"