name = "dhgate-monitor"
main = "worker_simple.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
BACKEND_URL = "https://your-python-app.railway.app"

[[routes]]
pattern = "dhgate-monitor.com/*"
zone_name = "dhgate-monitor.com"