name = "dhgate-monitor"
main = "cloudflare_app.js" # of "src/index.js" als dat je entrypoint is
compatibility_date = "2025-08-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# KV Namespace for data storage
[[kv_namespaces]]
binding = "DHGATE_MONITOR_KV"
id = "9e3e5971f9454b55b2241aeba6b1e1ba"

# Scheduled monitoring (daily at 09:00 UTC)
[triggers]
crons = ["0 9 * * *"]

# Custom domain routing
[[routes]]
pattern = "dhgate-monitor.com/*"
zone_name = "dhgate-monitor.com"

[[routes]]
pattern = "www.dhgate-monitor.com/*"
zone_name = "dhgate-monitor.com"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "dhgate-monitor"
database_id = "c81bf194-e0ca-4247-9086-cd5f57846846"

