name: 'DHgate Monitor - Cloud Selenium'

on:
  schedule:
    # Runs daily at 09:00 UTC (10:00 CET in winter, 11:00 CEST in summer)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  selenium-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 📦 Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-full.txt
        
    - name: 🌐 Setup Chrome browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: 🤖 Run DHgate Selenium monitoring
      env:
        ENVIRONMENT: production
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "🤖 Starting GitHub Actions DHgate monitoring..."
        echo "⏰ Timestamp: $(date)"
        echo "🌍 Environment: $ENVIRONMENT"
        
        # Update config with secrets
        python3 update_config_secrets.py
        
        # Run Selenium monitoring
        python3 run_monitor.py
        
    - name: 📊 Archive monitoring logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dhgate-monitoring-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
        if-no-files-found: warn