name: 'Selenium DHgate Check'

on:
  schedule:
    # Runs daily at 09:00 UTC (10:00 CET in winter, 11:00 CEST in summer)
    - cron: '0 9 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-full.txt
        
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1-3)
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}/chromedriver_linux64.zip"
        unzip /tmp/chromedriver.zip -d /tmp/
        sudo mv /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
    - name: Run monitoring
      env:
        ENVIRONMENT: production
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "🤖 Starting GitHub Actions DHgate monitoring..."
        echo "⏰ Timestamp: $(date)"
        echo "🌍 Environment: $ENVIRONMENT"
        
        # Update config with secrets
        python3 update_config_secrets.py
        
        # Run Selenium monitoring
        python3 run_monitor.py
        
        echo "✅ Monitoring completed!"
        
    - name: Show results
      if: always()
      run: |
        echo "📊 Monitoring Results:"
        if [ -d "logs" ]; then
          echo "=== Logs found ==="
          ls -la logs/
          if [ -f "logs/monitor.log" ]; then
            echo "=== Latest Monitor Log ==="
            tail -20 logs/monitor.log
          fi
        else
          echo "No logs directory found"
        fi